### ISSUE TITLE
Bianca's Checklist of Changes/Tweaks

### ISSUE THREAD

**Issue by brentrobbins** [variantstudios/greeleydowntown.com#132]
- [x] Can we hyperlink the title of events in Signature Events? The logo is hyperlinked but not the title.
- [ ] When you click on one of the Sig Events, can we have the option of seeing the others on the right nav (like on current site)?
- [x] Let’s delete the District Map under "Play"
- [x] Under "Business Incentives" under "Work," for some reason I can't edit the text in the Editor. Can you look into this? https://app.cloudcannon.com/editor#/site/19514/update/work/business-incentives/
